services:
  wotp-core:
    image: ghcr.io/raucheacho/wotp:{{.Version}}
    restart: always
    volumes:
      - ./data:/data
      - ../config.toml:/app/config.toml:ro
      - ../seed/templates.toml:/app/templates.toml:ro
    env_file: .env
    ports:
      - "{{.Port}}:{{.Port}}"
