package api

import (
	"context"
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/wotp/core/internal/store"
	"github.com/wotp/core/internal/whatsapp"
	"github.com/wotp/core/internal/ws"
)

// routeInboundMessage persists an inbound WhatsApp message to its
// conversation (creating the conversation on first contact) and returns the
// event enriched with the conversation's id/state, for forwarding to the
// project's webhook. wotp always forwards — it doesn't decide whether the
// receiving app's bot should act on a human-owned conversation, it just
// tells the app the conversation's current state (conversation_state in the
// enriched Data) and lets the app's own logic decide. The message is always
// recorded and broadcast over the WS hub too, so a human operator watching
// it live never misses anything.
//
// Split out from StartEventForwarder so this is unit-testable without
// needing a live whatsmeow connection.
//
// mediaDir is the directory inbound media files are written to (see
// project.Runtime.MediaDir). Passed explicitly rather than read off a
// Runtime so this stays unit-testable with a plain temp dir.
func routeInboundMessage(ctx context.Context, st store.ProjectStore, mediaDir string, evt whatsapp.Event) (whatsapp.Event, error) {
	conv, err := st.GetOrCreateConversation(ctx, evt.Phone)
	if err != nil {
		// Fail open: return the event unchanged rather than silently drop
		// an inbound message just because the conversation lookup had a
		// hiccup.
		return evt, err
	}

	var text, pushName, mediaKind, mediaMimeType string
	var mediaBytes []byte
	if data, ok := evt.Data.(map[string]interface{}); ok {
		text, _ = data["text"].(string)
		pushName, _ = data["pushName"].(string)
		mediaKind, _ = data["mediaKind"].(string)
		mediaMimeType, _ = data["mediaMimeType"].(string)
		mediaBytes, _ = data["mediaBytes"].([]byte)
	}

	at := evt.At
	if at.IsZero() {
		at = time.Now().UTC()
	}

	// evt.MessageID is external input on both backends (whatsmeow's
	// protocol, Meta's webhook JSON) — never trust it in a filesystem path
	// unchecked. A media message with an unsafe id still gets its
	// kind/mimetype recorded; only the file write is skipped.
	if mediaBytes != nil && !isSafeMediaFilename(evt.MessageID) {
		mediaBytes = nil
	}

	insertErr := st.InsertInboundMessage(ctx, &store.InboundMessage{
		ConversationID: conv.ID,
		Phone:          evt.Phone,
		Content:        text,
		PushName:       pushName,
		MessageID:      evt.MessageID,
		MediaKind:      mediaKind,
		MediaMimeType:  mediaMimeType,
		CreatedAt:      at,
	})

	if insertErr == nil && mediaBytes != nil {
		// Fail open on a write error — the message itself is already
		// recorded; a dev's bot will see media_kind set but GET
		// /v1/media/{id} will 404, which is the documented failure mode for
		// a failed download/write.
		_ = os.WriteFile(filepath.Join(mediaDir, evt.MessageID), mediaBytes, 0600)
	}

	evt.Data = map[string]interface{}{
		"text":               text,
		"pushName":           pushName,
		"conversation_id":    conv.ID,
		"conversation_state": conv.State,
	}
	return evt, insertErr
}

// isSafeMediaFilename reports whether id is safe to use as a bare filename
// under MediaDir — no path separators, no "..", not empty. MessageIDs are
// external input (whatsmeow's protocol, Meta's webhook JSON), never
// generated by wotp itself.
func isSafeMediaFilename(id string) bool {
	return id != "" && id == filepath.Base(id) && !strings.Contains(id, "..") && !strings.ContainsAny(id, `/\`)
}

func (s *Server) handleListConversations(w http.ResponseWriter, r *http.Request) {
	rt := s.runtime()
	convs, err := rt.Store.ListConversations(r.Context())
	if err != nil {
		s.logger.Error("failed to list conversations", "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to list conversations"})
		return
	}
	if convs == nil {
		convs = []store.Conversation{}
	}
	writeJSON(w, http.StatusOK, convs)
}

func (s *Server) handleGetConversation(w http.ResponseWriter, r *http.Request) {
	rt := s.runtime()
	conv, err := rt.Store.GetConversationByID(r.Context(), chi.URLParam(r, "id"))
	if err != nil {
		s.logger.Error("failed to get conversation", "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to get conversation"})
		return
	}
	if conv == nil {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": "conversation not found"})
		return
	}
	writeJSON(w, http.StatusOK, conv)
}

// conversationMessage unifies InboundMessage, GenericMessage (outbound), and
// OTPRequest rows into one chronological shape for GET .../messages — a
// human taking over needs to see the whole thread, OTPs included, not query
// three tables separately.
type conversationMessage struct {
	Direction string `json:"direction"` // "inbound" | "outbound"
	// Kind is "otp" for OTP sends, the outbound message's type
	// ("text"/"media") for generic sends, or an inbound media message's
	// MediaKind ("image"/"video"/"audio"/"document") — empty for a plain
	// inbound text/location message.
	Kind     string `json:"kind,omitempty"`
	Content  string `json:"content"`
	PushName string `json:"push_name,omitempty"`
	// MediaMimeType is set alongside Kind for an inbound media message —
	// see GET /v1/media/{message_id} to fetch the actual bytes.
	MediaMimeType string    `json:"media_mime_type,omitempty"`
	MessageID     string    `json:"message_id,omitempty"`
	Status        string    `json:"status,omitempty"`
	At            time.Time `json:"at"`
}

func (s *Server) handleGetConversationMessages(w http.ResponseWriter, r *http.Request) {
	rt := s.runtime()
	ctx := r.Context()

	conv, err := rt.Store.GetConversationByID(ctx, chi.URLParam(r, "id"))
	if err != nil {
		s.logger.Error("failed to get conversation", "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to get conversation"})
		return
	}
	if conv == nil {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": "conversation not found"})
		return
	}

	inbound, err := rt.Store.ListInboundMessagesByPhone(ctx, conv.Phone, 200)
	if err != nil {
		s.logger.Error("failed to list inbound messages", "conversation_id", conv.ID, "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to list messages"})
		return
	}
	outbound, err := rt.Store.GetGenericMessagesByPhone(ctx, conv.Phone, 200)
	if err != nil {
		s.logger.Error("failed to list outbound messages", "conversation_id", conv.ID, "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to list messages"})
		return
	}
	otps, err := rt.Store.GetOTPRequestsByConversationID(ctx, conv.ID, 200)
	if err != nil {
		s.logger.Error("failed to list otp requests", "conversation_id", conv.ID, "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to list messages"})
		return
	}

	merged := make([]conversationMessage, 0, len(inbound)+len(outbound)+len(otps))
	for _, m := range inbound {
		merged = append(merged, conversationMessage{
			Direction:     "inbound",
			Kind:          m.MediaKind,
			Content:       m.Content,
			PushName:      m.PushName,
			MediaMimeType: m.MediaMimeType,
			MessageID:     m.MessageID,
			At:            m.CreatedAt.UTC(),
		})
	}
	for _, m := range outbound {
		merged = append(merged, conversationMessage{
			Direction: "outbound",
			Kind:      m.MessageType,
			Content:   m.Content,
			MessageID: m.ID,
			Status:    m.Status,
			At:        m.CreatedAt.UTC(),
		})
	}
	for _, o := range otps {
		// Content is deliberately left empty — the code is bcrypt-hashed at
		// rest and was never surfaced anywhere before; Kind+Status is
		// enough for a caller to render "OTP · verified" without it.
		merged = append(merged, conversationMessage{
			Direction: "outbound",
			Kind:      "otp",
			MessageID: o.MessageID,
			Status:    string(o.Status),
			At:        o.CreatedAt.UTC(),
		})
	}
	// Sort by the actual time value, not a formatted string — RFC3339's
	// variable-width fractional seconds make lexicographic string
	// comparison unreliable across timestamps with different precision.
	sort.Slice(merged, func(i, j int) bool { return merged[i].At.Before(merged[j].At) })

	writeJSON(w, http.StatusOK, merged)
}

// ConversationStateChangeRequest is the optional JSON body for takeover and
// resume — both actor and reason are freeform and optional, but recording
// them (when the caller provides them) is what makes a takeover auditable
// instead of a silent state flip.
type ConversationStateChangeRequest struct {
	Actor  string `json:"actor,omitempty"`
	Reason string `json:"reason,omitempty"`
}

func (s *Server) handleTakeoverConversation(w http.ResponseWriter, r *http.Request) {
	s.setConversationState(w, r, store.ConversationStateHuman)
}

func (s *Server) handleResumeConversation(w http.ResponseWriter, r *http.Request) {
	s.setConversationState(w, r, store.ConversationStateBot)
}

func (s *Server) setConversationState(w http.ResponseWriter, r *http.Request, newState string) {
	rt := s.runtime()
	ctx := r.Context()
	id := chi.URLParam(r, "id")

	conv, err := rt.Store.GetConversationByID(ctx, id)
	if err != nil {
		s.logger.Error("failed to get conversation", "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to get conversation"})
		return
	}
	if conv == nil {
		writeJSON(w, http.StatusNotFound, map[string]string{"error": "conversation not found"})
		return
	}

	var req ConversationStateChangeRequest
	if r.Body != nil {
		_ = json.NewDecoder(r.Body).Decode(&req) // body is optional — actor/reason default to ""
	}

	if err := rt.Store.SetConversationState(ctx, id, newState, req.Actor, req.Reason); err != nil {
		s.logger.Error("failed to set conversation state", "conversation_id", id, "error", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "failed to update conversation"})
		return
	}

	s.wsHub.Broadcast(ws.Event{
		Type:      "conversation.state_changed",
		Phone:     conv.Phone,
		Payload:   map[string]string{"conversation_id": id, "state": newState},
		At:        time.Now().UTC().Format(time.RFC3339),
	})

	writeJSON(w, http.StatusOK, map[string]string{"state": newState})
}
