package keys

import (
	"context"
	"io"
	"log/slog"
	"path/filepath"
	"testing"

	"github.com/wotp/core/internal/store"
)

func newTestControlStore(t *testing.T) store.ControlStore {
	t.Helper()
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	s, err := store.NewSQLiteControlStore(filepath.Join(t.TempDir(), "control.db"), logger)
	if err != nil {
		t.Fatalf("NewSQLiteControlStore: %v", err)
	}
	t.Cleanup(func() { s.Close() })
	return s
}

func TestGenerateAndValidate_RoundTrip(t *testing.T) {
	cs := newTestControlStore(t)
	mgr := NewManager(cs)
	ctx := context.Background()

	key, err := mgr.Generate(ctx, TierAnon)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	tier, err := mgr.Validate(ctx, key.FullKey)
	if err != nil {
		t.Fatalf("Validate: %v", err)
	}
	if tier != TierAnon {
		t.Errorf("tier = %q, want %q", tier, TierAnon)
	}
}

func TestValidate_UnknownKeyErrors(t *testing.T) {
	cs := newTestControlStore(t)
	mgr := NewManager(cs)
	if _, err := mgr.Validate(context.Background(), "wotp_anon_deadbeefdeadbeef"); err == nil {
		t.Fatal("expected an error for an unknown key")
	}
}

// TestEnsureKeys_NeverConsultsTheEnvironment is a regression test for a real
// bug found via live testing: EnsureKeys used to always consult
// WOTP_ANON_KEY/WOTP_SERVICE_KEY, which collided with keys generated by a
// later call. Only EnsureKeysWithEnvFallback (used solely for wotp-core's
// own startup bootstrap) may import from the environment.
func TestEnsureKeys_NeverConsultsTheEnvironment(t *testing.T) {
	t.Setenv("WOTP_ANON_KEY", "wotp_anon_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
	t.Setenv("WOTP_SERVICE_KEY", "wotp_service_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")

	cs := newTestControlStore(t)
	mgr := NewManager(cs)
	ctx := context.Background()

	anon, service, err := mgr.EnsureKeys(ctx)
	if err != nil {
		t.Fatalf("EnsureKeys: %v", err)
	}
	if anon.FullKey == "wotp_anon_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" {
		t.Fatal("EnsureKeys must not import WOTP_ANON_KEY from the environment")
	}
	if service.FullKey == "wotp_service_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" {
		t.Fatal("EnsureKeys must not import WOTP_SERVICE_KEY from the environment")
	}

	if tier, err := mgr.Validate(ctx, anon.FullKey); err != nil || tier != TierAnon {
		t.Fatalf("validate generated anon key: tier=%q err=%v", tier, err)
	}
}

func TestEnsureKeysWithEnvFallback_ImportsFromEnvironment(t *testing.T) {
	t.Setenv("WOTP_ANON_KEY", "wotp_anon_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
	t.Setenv("WOTP_SERVICE_KEY", "wotp_service_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")

	cs := newTestControlStore(t)
	mgr := NewManager(cs)
	ctx := context.Background()

	anon, service, err := mgr.EnsureKeysWithEnvFallback(ctx)
	if err != nil {
		t.Fatalf("EnsureKeysWithEnvFallback: %v", err)
	}
	if anon.FullKey != "wotp_anon_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" {
		t.Fatalf("expected the env-provided WOTP_ANON_KEY to be imported, got %q", anon.FullKey)
	}
	if service.FullKey != "wotp_service_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" {
		t.Fatalf("expected the env-provided WOTP_SERVICE_KEY to be imported, got %q", service.FullKey)
	}

	if tier, err := mgr.Validate(ctx, anon.FullKey); err != nil || tier != TierAnon {
		t.Fatalf("validate imported anon key: tier=%q err=%v", tier, err)
	}
}

func TestEnsureKeys_IsIdempotent(t *testing.T) {
	cs := newTestControlStore(t)
	mgr := NewManager(cs)
	ctx := context.Background()

	anon1, service1, err := mgr.EnsureKeys(ctx)
	if err != nil {
		t.Fatalf("EnsureKeys (first call): %v", err)
	}
	if anon1 == nil || service1 == nil {
		t.Fatalf("expected both keys to be generated on first call, got anon=%v service=%v", anon1, service1)
	}

	anon2, service2, err := mgr.EnsureKeys(ctx)
	if err != nil {
		t.Fatalf("EnsureKeys (second call): %v", err)
	}
	if anon2 != nil || service2 != nil {
		t.Fatalf("expected nil (already exists) on second call, got anon=%v service=%v", anon2, service2)
	}
}

func TestRegenerateAll_InvalidatesOldKey(t *testing.T) {
	cs := newTestControlStore(t)
	mgr := NewManager(cs)
	ctx := context.Background()

	oldKey, err := mgr.Generate(ctx, TierAnon)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	newKey, err := mgr.RegenerateAll(ctx, TierAnon)
	if err != nil {
		t.Fatalf("RegenerateAll: %v", err)
	}
	if newKey.FullKey == oldKey.FullKey {
		t.Fatal("expected a fresh key after regeneration")
	}

	if _, err := mgr.Validate(ctx, oldKey.FullKey); err == nil {
		t.Fatal("old key should no longer validate after regeneration")
	}
	if tier, err := mgr.Validate(ctx, newKey.FullKey); err != nil || tier != TierAnon {
		t.Fatalf("new key should validate: tier=%q err=%v", tier, err)
	}
}
